medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost       # Connects to your Docker container
      user: postgres
      password: password    # Matches docker-compose.yml
      port: 5432
      dbname: medical_warehouse
      schema: public
      threads: 1